// vite plugin to export method names from backend + native handlers to 'shared/apiMethods.ts'

import fs from 'fs';
import { resolve } from 'path';
import type { PluginOption } from 'vite';

const electronApiMethods: PluginOption = {
    name: 'export-api-methods',
    buildStart() {
        const mainPath = resolve(__dirname, 'electron/main.ts');
        const apiMethodsPath = resolve(__dirname, 'packages/shared/src/utils/apiMethods.ts');

        // Extract method names from createHandlers() return object in main.ts.
        // Backend methods use wrap0/wrap1 wrappers, native methods use async (.
        const content = fs.readFileSync(mainPath, 'utf-8');
        const methodNames = [...content.matchAll(/^\s+([a-zA-Z]+):\s+(wrap[01]\(|async\s+\()/gm)].map((m) => m[1]);

        const names = [...new Set(methodNames)]
            .sort()
            .map((name) => `'${name}'`)
            .join(',\n    ');

        let result = '// This file is auto-generated by vite-export-api-methods.ts';
        result += `\nexport const apiMethods = [\n    ${names},\n] as const;\n`;

        fs.writeFileSync(apiMethodsPath, result);
    },
};

export default electronApiMethods;
