// vite plugin to export method names from backend + native handlers to 'shared/apiMethods.ts'

import fs from 'fs';
import { resolve } from 'path';
import type { PluginOption } from 'vite';

const electronApiMethods: PluginOption = {
    name: 'export-api-methods',
    buildStart() {
        console.log('Exporting API method names to src/shared/apiMethods.ts...');
        const appPath = resolve(__dirname, 'src/backend/app.ts');
        const mainPath = resolve(__dirname, 'src/electron/main.ts');
        const apiMethodsPath = resolve(__dirname, 'src/shared/apiMethods.ts');

        // Extract backend method names from app.ts: methodName: async (ps) => {
        // Exclude getter/IIFE patterns where name: (() => { ... })()
        const appContent = fs.readFileSync(appPath, 'utf-8');
        const appLines = appContent.split('\n');
        const backendMethodMatches = [...appContent.matchAll(/^\s+([a-zA-Z]+):\s+(async\s+)?\(/gm)];
        const backendMethods = backendMethodMatches
            .filter((m) => {
                const lineIndex = appContent.substring(0, m.index).split('\n').length - 1;
                const line = appLines[lineIndex];
                // Skip IIFE getter patterns like: name: (() => { ... })()
                return !/:\s*\(\(\)/.test(line);
            })
            .map((m) => m[1]);

        // Extract native method names from main.ts: methodName: async (ps) => { in createNativeHandlers
        const handlersContent = fs.readFileSync(mainPath, 'utf-8');
        const nativeMethods = [...handlersContent.matchAll(/^\s+([a-zA-Z]+):\s+async\s+\(/gm)].map((m) => m[1]);

        const allMethods = [...new Set([...backendMethods, ...nativeMethods])].sort();
        const names = allMethods.map((name) => `'${name}'`).join(',\n    ');

        let content = '// This file is auto-generated by vite-export-api-methods.ts';
        content += `\nexport const apiMethods = [\n    ${names},\n] as const;\n`;

        fs.writeFileSync(apiMethodsPath, content);
    },
};

export default electronApiMethods;
