import type { DbType } from '@utils/appClient';

const MYSQL_DATA_TYPES = [
    'bit',
    'int',
    'integer',
    'tinyint',
    'smallint',
    'mediumint',
    'bigint',
    'float',
    'double',
    'double precision',
    'real',
    'decimal',
    'dec',
    'numeric',
    'fixed',
    'blob',
    'bool',
    'boolean',
    'date',
    'datetime',
    'timestamp',
    'time',
    'year',
    'char',
    'nchar',
    'national char',
    'varchar',
    'nvarchar',
    'national varchar',
    'text',
    'tinyblob',
    'tinytext',
    'mediumblob',
    'mediumtext',
    'longblob',
    'longtext',
    'enum',
    'set',
    'binary',
    'varbinary',
    'json',
    'geometry',
    'point',
    'linestring',
    'polygon',
    'multipoint',
    'multilinestring',
    'multipolygon',
    'geometrycollection',
    'vector',
    'uuid',
    'inet4',
    'inet6',
];

const POSTGRES_DATA_TYPES = [
    'int',
    'int2',
    'int4',
    'int8',
    'smallint',
    'integer',
    'bigint',
    'decimal',
    'numeric',
    'real',
    'float',
    'float4',
    'float8',
    'double precision',
    'money',
    'character varying',
    'varchar',
    'character',
    'char',
    'text',
    'citext',
    'hstore',
    'bytea',
    'bit',
    'varbit',
    'bit varying',
    'timetz',
    'timestamptz',
    'timestamp',
    'timestamp without time zone',
    'timestamp with time zone',
    'date',
    'time',
    'time without time zone',
    'time with time zone',
    'interval',
    'bool',
    'boolean',
    'enum',
    'point',
    'line',
    'lseg',
    'box',
    'path',
    'polygon',
    'circle',
    'inet',
    'macaddr',
    'macaddr8',
    'tsvector',
    'tsquery',
    'uuid',
    'xml',
    'json',
    'jsonb',
    'jsonpath',
    'int4range',
    'int8range',
    'numrange',
    'tsrange',
    'tstzrange',
    'daterange',
    'int4multirange',
    'int8multirange',
    'nummultirange',
    'tsmultirange',
    'tstzmultirange',
    'datemultirange',
    'geometry',
    'geography',
    'cube',
    'ltree',
    'vector',
    'halfvec',
];

const SQLITE_DATA_TYPES = [
    'int',
    'integer',
    'tinyint',
    'smallint',
    'mediumint',
    'bigint',
    'unsigned big int',
    'int2',
    'int8',
    'integer',
    'character',
    'varchar',
    'varying character',
    'nchar',
    'native character',
    'nvarchar',
    'text',
    'clob',
    'text',
    'blob',
    'real',
    'double',
    'double precision',
    'float',
    'real',
    'numeric',
    'decimal',
    'boolean',
    'date',
    'time',
    'datetime',
    'json',
];

export function getDbColumnDataTypeOptions(driver: DbType | undefined, currentValue?: string | null) {
    const baseOptions = driver === 'mysql' ? MYSQL_DATA_TYPES : driver === 'postgresql' ? POSTGRES_DATA_TYPES : SQLITE_DATA_TYPES;
    const normalizedCurrentValue = currentValue?.trim();

    const opts = [...new Set([...(normalizedCurrentValue ? [normalizedCurrentValue] : []), ...baseOptions])];

    return opts.map((value) => ({ value: value, label: value }));
}
