import type { ChildProcess } from 'child_process';
import { exec, execSync } from 'child_process';
import fs from 'fs';
import { join, resolve } from 'path';
import type { PluginOption } from 'vite';
import { appConfig } from './helpers';

type Options = {
    app: string;
    main: string;
    preload: string;
    devServer: string;
    apiMethods: string;

    externalize?: string[];
};

function generateApiMethods(paths: Options) {
    // Extract backend method names from app.ts: methodName: async (ps) => {
    // Exclude getter/IIFE patterns where name: (() => { ... })()
    const appContent = fs.readFileSync(paths.app, 'utf-8');
    const appLines = appContent.split('export const app = {').pop()!.split('\n');
    const backendMethodMatches = [...appContent.matchAll(/^    ([a-zA-Z]+):\s+(async\s+)?\(/gm)];
    const backendMethods = backendMethodMatches
        .filter((m) => {
            const lineIndex = appContent.substring(0, m.index).split('\n').length - 1;
            const line = appLines[lineIndex];
            // Skip IIFE getter patterns like: name: (() => { ... })()
            return !/:\s*\(\(\)/.test(line);
        })
        .map((m) => m[1]);

    // Extract native method names from main.ts: methodName: async (ps) => { in createNativeHandlers
    const handlersContent = fs.readFileSync(paths.main, 'utf-8');
    const nativeMethods = [...handlersContent.matchAll(/^\s+([a-zA-Z]+):\s+async\s+\(/gm)].map((m) => m[1]);

    const allMethods = [...new Set([...backendMethods, ...nativeMethods])].sort();
    const names = allMethods.map((name) => `'${name}'`).join(',\n    ');

    let content = '// This file is auto-generated by src/electronUtils/vite-plugin.ts';
    content += `\nexport const apiMethods = [\n    ${names},\n] as const;\n`;

    fs.writeFileSync(paths.apiMethods, content);
}

const buildElectronAssets = (paths: Options) => {
    const projectRoot = resolve(import.meta.dirname ?? process.cwd(), '../..');
    const outDir = resolve(projectRoot, 'dist-electron');

    // Clean stale electron builds — vite only empties its own outDir (dist/),
    // not dist-electron/.  rolldown's caching can also skip recompilation.
    if (fs.existsSync(outDir)) {
        fs.rmSync(outDir, { recursive: true, force: true });
    }
    fs.mkdirSync(outDir, { recursive: true });

    const cfgs = [
        { src: paths.main, out: join(outDir, 'main.cjs'), external: ['electron', 'better-sqlite3', ...(paths.externalize || [])] },
        { src: paths.preload, out: join(outDir, 'preload.cjs'), external: ['electron'] },
        { src: paths.devServer, out: join(outDir, 'backend.cjs'), external: ['better-sqlite3'] },
    ];
    console.log('⚡ [Rolldown] Compiling Electron main, preload, and backend targets...');
    for (const cfg of cfgs) {
        const externalFlags = cfg.external.map((id) => `-e ${id}`).join(' ');
        execSync(`bunx rolldown ${cfg.src} --file=${cfg.out} ${externalFlags} --platform=node --format=cjs --no-code-splitting`, { stdio: 'inherit' });
    }
};

let electronProcess: ChildProcess | null = null;

function killStaleServers(...ports: number[]) {
    for (const port of ports) {
        try {
            execSync(`lsof -ti:${port} | xargs kill -9 2>/dev/null || true`, { stdio: 'ignore' });
        } catch {
            // port already free, nothing to do
        }
    }
}

function watchDevServer(server: any, paths: Options) {
    const isDesktopMode = server.config.mode === 'desktop';

    if (!isDesktopMode) {
        console.log('🌐 Browser Dev Mode active. Mounting devServer via Vite ModuleRunner...');
        server.httpServer?.once('listening', async () => {
            try {
                const backendRunner = (server.environments as any).ssr?.runner;
                if (backendRunner) {
                    await backendRunner.import(paths.devServer);
                    console.log('🚀 Backend devServer successfully instantiated inside Vite.');
                } else {
                    console.warn('⚠️ SSR environment runner not found.');
                }
            } catch (error) {
                console.error('❌ Vite failed to load your background devServer script:', error);
            }
        });
    } else {
        console.log('🖥️  Desktop Dev Mode active. Preparing asset dependencies...');
        buildElectronAssets(paths);

        server.httpServer?.once('listening', () => {
            const addressInfo = server.httpServer?.address();
            if (addressInfo) {
                console.log('📱 Frontend asset stream active. Instantiating Electron window...');

                electronProcess = exec('electron .', {
                    env: { ...process.env, VITE_DEV2: 'true' },
                });

                electronProcess.on('error', (err) => {
                    // Fallback restoration in case of an instant boot failure
                    // fs.writeFileSync(packageJsonPath, rawPackageJson);
                    console.error('Electron run failed:', err);
                });
            }
        });
    }

    process.on('exit', () => {
        electronProcess?.kill();
    });
}

const electronPlugin = (paths: Options): PluginOption => {
    paths.app = resolve(paths.app);
    paths.main = resolve(paths.main);
    paths.preload = resolve(paths.preload);
    paths.devServer = resolve(paths.devServer);
    paths.apiMethods = resolve(paths.apiMethods);

    return {
        name: 'export-api-methods',

        config() {
            return {
                environments: {
                    ssr: {
                        resolve: {
                            conditions: ['node'],
                        },
                    },
                },
            };
        },
        buildStart() {
            // kill running processes for both dev and build
            killStaleServers(appConfig.apiPort, appConfig.vuePort);
            generateApiMethods(paths);
        },
        configureServer(server) {
            server.watcher.add([paths.app, paths.main]);
            server.watcher.on('change', (file) => {
                if (file === paths.app || file === paths.main) {
                    generateApiMethods(paths);
                }
            });

            watchDevServer(server, paths);
        },

        closeBundle() {
            buildElectronAssets(paths);
        },
    };
};

export default electronPlugin;
